### PR TITLE
added gems and set up the assets to serve the app with bootstrap properly

### PR DESCRIPTION
**Pull request by JYoung217**
@nilbus - coming up with an error after running rails s

OpenSSL::Cipher::CipherError in DoctorsController#index
Illegal key size: possibly you need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for your JRE

I will look into this more tomorrow, but if you know what it is, let me know so I can fix it!

### CODE REVIEW

**Comment by nilbus** [comment]
> OpenSSL::Cipher::CipherError in DoctorsController#index
> Illegal key size: possibly you need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for your JRE

This problem is local to your JRE, and I would have to google it.

We'll want to test on JRuby and with Tomcat, so it'll be good to get this working. However in general, I recommend just using standard MRI ruby for development rather than running on JRuby, just because it's faster.

**Comment by nilbus** [comment]
I think the only thing missing for the bootstrap setup is an application layout that builds the bootstrap container, so we have a common HTML header, nav, container, etc. for every page. Convention is to name it `app/views/layouts/application.html.erb`, and configure it for use on every page in `application_controller.rb` with `layout :application`. Then views in every controller that inherits from `ApplicationController` like the `DoctorsController` you will automatically use that layout.

**Comment by nilbus** [comment]
Since our sharing model assumes external sharing, not just other users of the same system, I'm not sure that we'll want to implement a doctors controller/model/index. We can simplify by just assuming that some doctor is already logged in and is the sole user who can log in. Later we might mock a login, but I think there's no need to differentiate between doctors behind the scenes.

Instead, what do you think about implementing a welcome controller that has a single view with a splash page that introduces our app? Something similar in concept to these but simpler: http://www.webdesignerhub.com/best-responsive-bootstrap-landing-page-templates/

**Comment by JYoung217** [comment]
I figured out the OpenSSL problem. If you run into a problem, look into this tutorial: http://deployingjruby.blogspot.com/2013/05/how-to-run-rails-400rc1-on-jruby.html

I'll look into creating some standard layouts later this week and will get that up. For now, I think merging my branch won't break anything.

**Comment by nilbus** [comment]
Cool. I'll merge the bootstrap stuff.

**Pull request closed without merging**
